export const storefrontProducts = [
  {
    slug: 'herbal-shampoo',
    name: 'HERBAL SHAMPOO',
    description: 'A gentle yet effective cleanser formulated with botanical ingredients to remove buildup, excess oil, and impurities while supporting a healthy scalp environment for stronger, healthier hair.',
    functionTag: 'Cleanse',
    price: 6500,
    stockQuantity: 50,
    image: 'shampoo-herbal-cleanse.png',
    tags: ['shampoo', 'cleanse', 'herbal'],
    rating: '*****',
    reviews: 243,
    badge: null,
  },
  {
    slug: 'velvet-curls-conditioner',
    name: 'VELVET CURLS CONDITIONER',
    description: 'A moisturizing conditioner designed to soften, detangle, and improve manageability while helping to reduce breakage and enhance curl definition.',
    functionTag: 'Nourish',
    price: 6500,
    stockQuantity: 45,
    image: 'conditioner-velvet-curls.png',
    tags: ['conditioner', 'curls', 'moisture'],
    rating: '*****',
    reviews: 117,
    badge: null,
  },
  {
    slug: 'pure-moisture-leave-in-conditioner',
    name: 'PURE MOISTURE LEAVE-IN CONDITIONER',
    description: 'A lightweight leave-in treatment that delivers lasting hydration, improves softness, and helps keep hair manageable, smooth, and protected throughout the day.',
    functionTag: 'Nourish',
    price: 6500,
    stockQuantity: 35,
    image: 'leave-in-conditioner.png',
    tags: ['leave-in', 'conditioner', 'moisture'],
    rating: '*****',
    reviews: 164,
    badge: null,
  },
  {
    slug: 'royal-soft-hair-butter',
    name: 'ROYAL SOFT HAIR BUTTER',
    description: 'A rich blend of nourishing butters and oils that helps seal in moisture, soften strands, and restore dry, dull hair without weighing it down.',
    functionTag: 'Nourish',
    price: 6500,
    stockQuantity: 25,
    image: 'hair-butter.png',
    tags: ['butter', 'moisture', 'shea'],
    rating: '*****',
    reviews: 128,
    badge: null,
  },
  {
    slug: 'hair-growth-cream',
    name: 'HAIR GROWTH CREAM',
    description: 'A nutrient-rich hair cream formulated to moisturize, strengthen, and support healthy hair growth while reducing dryness and breakage.',
    functionTag: 'Nourish',
    price: 6000,
    stockQuantity: 50,
    image: 'herbal-growth-cream.png',
    tags: ['cream', 'growth', 'moisture'],
    rating: '*****',
    reviews: 201,
    badge: null,
  },
  {
    slug: 'deep-conditioner',
    name: 'DEEP CONDITIONER',
    description: 'An intensive treatment designed to deeply nourish, strengthen, and restore moisture to dry, damaged, or brittle hair for improved elasticity and shine.',
    functionTag: 'Nourish',
    price: 8500,
    stockQuantity: 20,
    image: 'deep-conditioner.png',
    tags: ['conditioner', 'deep', 'treatment'],
    rating: '*****',
    reviews: 209,
    badge: null,
  },
  {
    slug: 'detangling-spray',
    name: 'DETANGLING SPRAY',
    description: 'A lightweight detangling spray that helps reduce knots, improve slip, and make styling easier while providing hydration and softness.',
    functionTag: 'Nourish',
    price: 7000,
    stockQuantity: 60,
    image: 'tangle-tamer.png',
    tags: ['spray', 'detangle', 'tangle'],
    rating: '*****',
    reviews: 96,
    badge: null,
  },
  {
    slug: 'hydra-root-therapy-anti-dandruff-cream',
    name: 'HYDRA ROOT THERAPY ANTI-DANDRUFF CREAM',
    description: 'A soothing scalp treatment formulated to help relieve dryness, itching, flakes, and scalp discomfort while promoting a healthier scalp environment.',
    functionTag: 'Nourish',
    price: 8000,
    stockQuantity: 15,
    image: 'anti-dandruff-cream.png',
    tags: ['cream', 'anti-dandruff', 'scalp', 'dandruff'],
    rating: '*****',
    reviews: 142,
    badge: null,
  },
  {
    slug: 'edge-growth-cream',
    name: 'EDGE GROWTH CREAM',
    description: 'A targeted formula designed to nourish fragile edges, reduce breakage, and support the appearance of fuller, healthier-looking hairlines.',
    functionTag: 'Nourish',
    price: 5000,
    stockQuantity: 40,
    image: 'edge-growth-cream.png',
    tags: ['cream', 'edges', 'growth', 'bestseller'],
    rating: '*****',
    reviews: 186,
    badge: 'Bestseller',
  },
  {
    slug: 'root-revival-ayurvedic-hair-oil',
    name: 'ROOT REVIVAL AYURVEDIC HAIR OIL',
    description: 'A carefully crafted blend of Ayurvedic herbs and nourishing oils designed to support scalp health, strengthen roots, and encourage healthier hair growth.',
    functionTag: 'Protect',
    price: 7000,
    stockQuantity: 30,
    image: 'root-revival-oil.png',
    tags: ['oil', 'ayurvedic', 'growth', 'roots'],
    rating: '*****',
    reviews: 319,
    badge: 'Customer Pick',
  },
  {
    slug: 'beard-oil',
    name: 'BEARD OIL',
    description: 'A lightweight grooming oil that softens beard hair, moisturizes the skin beneath, and promotes a healthier, well-maintained beard.',
    functionTag: 'Nourish',
    price: 5000,
    stockQuantity: 25,
    image: 'IMG_3525.PNG',
    tags: ['oil', 'beard', 'grooming'],
    rating: '*****',
    reviews: 88,
    badge: null,
  },
]

export const storefrontProductBySlug = new Map(storefrontProducts.map((product, index) => [product.slug, { ...product, storefrontOrder: index }]))
